spring:
  datasource:
    url: jdbc:mysql://sh-cdb-ow7uekkj.sql.tencentcdb.com:63183/recycle?characterEncoding=utf-8&useSSL=false
    username: root
    password: recycle123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true

  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**

  # 这个开发配置为false，避免改了模板还要重启服务器
  thymeleaf:
    cache: false
  # 这个是配置模板路径的，默认就是templates，可不用配置
    prefix: classpath:/templates/
  # 这个可以不配置，检查模板位置
    check-template-location: true
  # 下面3个不做解释了，可以不配置
    suffix: .html
    encoding: UTF-8

wechat:
  mpAppId: wx05799f115ff77cec
  mpAppSecret: 3df4cc7b7194ae72a02f24d00f833def