spring:
  datasource:
    url: jdbc:mysql://sh-cdb-ow7uekkj.sql.tencentcdb.com:63183/recycle?useUnicode=true&useSSL=false
    username: root
    password: recycle123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4

  #jpa
  jpa:
    show-sql: true
  #重定向转发配置
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**

  # 这个开发配置为false，避免改了模板还要重启服务器
  thymeleaf:
    cache: false
  # 这个是配置模板路径的，默认就是templates，可不用配置
    prefix: classpath:/templates/
  # 这个可以不配置，检查模板位置
    check-template-location: true
  # 下面3个不做解释了，可以不配置
    suffix: .html
    encoding: UTF-8

  #redis配置
  redis:
    database: 0
    host: 111.231.132.76
    port: 6379
    paasword:
    timeout: 1000ms

#微信相关配置
wechat:
  mpAppId: wx05799f115ff77cec
  mpAppSecret: 3df4cc7b7194ae72a02f24d00f833def
  miniapp:
    appid: wxa6dca10c030f20e3
    secret: ae65701b457671a2898affbaab0008a6
    token:
    aesKey:
    msgDataFormat: JSON
#日志配置
logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG
debug: true


